apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: maps5-monitor
  name: maps5-monitor
  namespace: maps5 
spec:
  endpoints:
    - interval: 30s
  port: http
  scheme: http
  selector:
    matchLabels:
      project: maps5
